//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContingencyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dungeon
    {
        public int Dungeon_ID { get; set; }
        public string Username { get; set; }
        public string PlayersInvited { get; set; }
        public string DungeonData { get; set; }
        public string PlayerPos { get; set; }
    
        public virtual Dungeon Dungeon1 { get; set; }
        public virtual Dungeon Dungeon2 { get; set; }
    }
}
