//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContingencyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public string Name { get; set; }
        public int HP { get; set; }
        public string Description { get; set; }
        public string Actions { get; set; }
        public string Abilities { get; set; }
        public string Stats { get; set; }
        public string AC { get; set; }
        public string CR { get; set; }
    }
}
